08-forms-fetch-api-part-2\1-product-form-v1
js-tasks-ru/js-20221021_kulikusya pull request #10
Opened 2022-11-23 18:40 UTC by AntonKulikovP

2022-11-23 18:41 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-24 16:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-11-25 13:44 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +    return new URL(this._categoriesEndpoint, BACKEND_URL);
может не через метод объявить а через св-во в конструкторе?

2022-11-25 13:46 UTC, dosandk requested changes
не нашел отправки данных на бекенд, где сохранение товара?

2022-12-04 17:07 UTC, dosandk approved these changes
good 👍

2022-12-04 17:07 UTC, merged